spring:
  cache:
    type: redis
  data:
    redis:
      database: 0
      host: localhost
      password:
      port: 6379
      ssl:
        enabled: false
server:
  base:
    url: http://localhost:8080/