spring:
  cache:
    type: redis
  data:
    redis:
      database: 0
      host: toggle-service.redis.cache.windows.net
      password: ${REDIS_PRIMARY_PASSWORD}
      port: 6380
      ssl:
        enabled: true

server:
  fraud:
    url: https://www.ipqualityscore.com/api/json/url/
    token: ${FRAUD_API_TOKEN}
  base:
    url: https://short-urls.azurewebsites.net/