spring:
  cache:
    type: simple
  data:
    redis:
      database: 0
      host: localhost
      password:
      port: 6379

server:
  fraud:
    url: https://www.ipqualityscore.com/api/json/url/
    token: ${FRAUD_API_TOKEN}
  base:
    url: http://localhost:8080/