spring:
  cache:
    type: redis
  data:
    redis:
      database: 0
      host: toggle-service.redis.cache.windows.net
      password: ${REDIS_PRIMARY_PASSWORD}
      port: 6380
      ssl:
        enabled: true

server:
  base:
    url: https://short-urls.azurewebsites.net/