spring:
  cache:
    type: redis
  data:
    redis:
      database: 0
      host: short-urls.azurewebsites.net
      password: ${REDIS_PRIMARY_PASSWORD}
      port: 6380
      ssl:
        enabled: true